---
- name: Manage Credentials Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_credentials_secure_logging }}"
  block:
    - name: Credentials | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_credentials_async_concurrency | int }}"

    - name: Credentials | Process in batches
      ansible.builtin.include_tasks:
        file: process_credential_batch.yml
      loop: "{{ range(0, (credentials if credentials is defined else controller_credentials) | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ (((credentials if credentials is defined else controller_credentials) | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __credentials_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __credentials_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __credentials_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __credentials_job_async_results_item
        label: "Cleaning up job results file: {{ __credentials_job_async_results_item.results_file | default('Unknown') }}"

- name: Add roles to credentials
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_roles
  when: aap_configuration_apply_object_roles
  vars:
    controller_roles: "{{ _controller_roles | from_yaml | default([], true) | list }}"
    _item_list: "{{ credentials if credentials is defined else controller_credentials }}"
    _controller_roles: |
      {% for _item in _item_list %}
      {% if _item.roles is defined %}
      {% for _role in _item.roles.keys() %}
      - role: "{{ _role }}"
        credentials:
          - "{{ _item.name }}"
        teams: "{{ _item.roles[_role].teams | default(omit) }}"
        users: "{{ _item.roles[_role].users | default(omit) }}"
      {% endfor %}
      {% endif %}
      {% endfor %}
...
