---
- name: process_credential_batch | Get current batch
  ansible.builtin.set_fact:
    __current_batch: "{{ (credentials if credentials is defined else controller_credentials)[__batch_start_index | int : __batch_start_index | int + __batch_size | int] }}"

- name: process_credential_batch | Configuration (Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }})
  ansible.controller.credential:
    name: "{{ __controller_credentials_item.name | mandatory }}"
    new_name: "{{ __controller_credentials_item.new_name | default(omit, true) }}"
    copy_from: "{{ __controller_credentials_item.copy_from | default(omit, true) }}"
    description: "{{ __controller_credentials_item.description | default(('' if controller_configuration_credentials_enforce_defaults else omit), true) }}"
    organization: "{{ __controller_credentials_item.organization.name | default(__controller_credentials_item.organization | default(omit, true)) }}"
    credential_type: "{{ __controller_credentials_item.credential_type.name | default(__controller_credentials_item.credential_type | mandatory) }}"
    inputs: "{{ __controller_credentials_item.inputs | default(({} if controller_configuration_credentials_enforce_defaults else omit), true) }}"
    user: "{{ __controller_credentials_item.user.username | default(__controller_credentials_item.user | default(omit, true)) }}"
    team: "{{ __controller_credentials_item.team.name | default(__controller_credentials_item.team | default(omit, true)) }}"
    update_secrets: "{{ __controller_credentials_item.update_secrets | default(true if controller_configuration_credentials_enforce_defaults else omit) }}"
    state: "{{ __controller_credentials_item.state | default(platform_state | default('present')) }}"
    controller_username: "{{ aap_username | default(omit, true) }}"
    controller_password: "{{ aap_password | default(omit, true) }}"
    controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
    controller_host: "{{ aap_hostname | default(omit, true) }}"
    request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ __current_batch }}"
  loop_control:
    loop_var: __controller_credentials_item
    label: "{{ __operation.verb }} Credential {{ __controller_credentials_item.name }}"
    pause: "{{ controller_configuration_credentials_loop_delay }}"
  async: "{{ ansible_check_mode | ternary(0, 1000) }}"
  poll: 0
  register: __credentials_batch_async
  changed_when: (__credentials_batch_async.changed if ansible_check_mode else false)
  vars:
    __operation: "{{ operation_translate[__controller_credentials_item.state | default(platform_state) | default('present')] }}"

- name: process_credential_batch | Flag for errors (check mode only)
  ansible.builtin.set_fact:
    error_flag: true
  when: ansible_check_mode and __credentials_batch_async.failed is defined and __credentials_batch_async.failed

- name: process_credential_batch | Wait for batch to complete
  ansible.builtin.include_role:
    name: infra.aap_configuration.collect_async_status
  loop: "{{ __credentials_batch_async.results }}"
  loop_control:
    loop_var: __credentials_job_async_results_item
    label: "{{ __operation.verb }} Credential {{ __credentials_job_async_results_item.__controller_credentials_item.name }} | Wait for finish the credential {{ __operation.action }}"
  when:
    - not ansible_check_mode
    - __credentials_job_async_results_item.ansible_job_id is defined
  vars:
    cas_secure_logging: "{{ controller_configuration_credentials_secure_logging }}"
    cas_async_delay: "{{ controller_configuration_credentials_async_delay }}"
    cas_async_retries: "{{ controller_configuration_credentials_async_retries }}"
    cas_job_async_results_item: "{{ __credentials_job_async_results_item }}"
    cas_register_subvar: controller_credentials
    cas_error_list_var_name: "controller_credentials_errors"
    __operation: "{{ operation_translate[__credentials_job_async_results_item.__controller_credentials_item.state | default(platform_state) | default('present')] }}"
    cas_object_label: "{{ __operation.verb }} Credential {{ __credentials_job_async_results_item.__controller_credentials_item.name }} | Wait for finish the credential {{ __operation.action }}"

- name: process_credential_batch | Delay between batches
  ansible.builtin.pause:
    seconds: "{{ controller_configuration_credentials_batch_delay }}"
  when:
    - not ansible_check_mode
    - controller_configuration_credentials_batch_delay | int > 0
...
