---
- name: async_hub_ee_registry_index | An async_hub_ee_registry_index block
  block:
    - name: async_hub_ee_registry_index | Managing hub ee registry_index | Wait for finish the hub ee registry index operation
      ansible.builtin.async_status:
        jid: "{{ __ee_registry_indexes_job_async_result_item.ansible_job_id }}"
      register: __ee_registry_indexes_job_async_result
      until: __ee_registry_indexes_job_async_result.finished
      retries: "{{ hub_configuration_ee_registry_index_async_retries }}"
      delay: "{{ hub_configuration_ee_registry_index_async_delay }}"
  rescue:
    - name: async_hub_ee_registry_index | Load error details
      ansible.builtin.include_vars:
        file: "{{ __ee_registry_indexes_job_async_result.results_file }}"
        name: __error_data

    - name: async_hub_ee_registry_index | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_hub_ee_registry_index | Building list of not processed hub ee registry index
      ansible.builtin.set_fact:
        __hub_ee_registry_index_error_list: "{{ __hub_ee_registry_index_error_list | default([]) + [
                                                                                  {
                                                                                   'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                   'error': __error_data['msg'] | default('')
                                                                                  }
                                                                                 ]
                                            }}"
...