---
# tasks file for meta_dependency_check
- name: "Set aap_version fact"
  ansible.builtin.set_fact:
    aap_version: >-
      {{
        lookup(
          'ansible.platform.gateway_api',
          'api/gateway/v1/ping',
          host=aap_hostname,
          verify_ssl=aap_validate_certs
        ).version
        | default('0.0.0')
      }}

- name: "Assert that the AAP version is 2.5 or greater"
  ansible.builtin.assert:
    that:
      - "aap_version is version('2.5', '>=')"
    fail_msg: "This collection is only supported on AAP 2.5+. Use infra.controller_configuration for earlier AAP/Ansible Tower versions."

- name: Print dependency check status
  ansible.builtin.debug:
    msg: "{{ controller_dependency_check | bool | ternary(__depdency_check_active_msg, __depdency_check_inactive_msg) }}"
  vars:
    __depdency_check_active_msg: Dependency check is active. Required collections presence will be verified.
    __depdency_check_inactive_msg: Dependency check is deactivated. Required collections presence will not be verified. This might cause failure in the next tasks.

- name: Dependency check block
  when: controller_dependency_check | bool
  block:
    - name: Check awx.awx is installed
      ansible.builtin.command: ansible-galaxy collection verify awx.awx
      failed_when: false
      changed_when: false
      register: upstream_dep

    - name: Check ansible.controller is installed
      ansible.builtin.command: ansible-galaxy collection verify ansible.controller
      failed_when: false
      changed_when: false
      register: downstream_dep

    - name: Ensure one is installed
      ansible.builtin.fail:
        msg: One of awx.awx or ansible.controller must be installed
      when:
        - "'ERROR!' in upstream_dep.stderr"
        - "'ERROR!' in downstream_dep.stderr"

...
