---
- name: Manage Controller Schedules Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_schedules_secure_logging }}"
  block:
    - name: Schedules | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_schedules_async_concurrency | int }}"

    - name: Schedules | Process in batches
      ansible.builtin.include_tasks:
        file: process_schedule_batch.yml
      loop: "{{ range(0, (schedules if schedules is defined else controller_schedules) | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ (((schedules if schedules is defined else controller_schedules) | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __controller_schedule_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __controller_schedule_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __schedules_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __controller_schedule_job_async_results_item
        label: "Cleaning up job results file: {{ __controller_schedule_job_async_results_item.results_file | default('Unknown') }}"
...
