---
# defaults file for global_vars
aap_request_timeout: 10
operation_translate:
  present:
    verb: Create/Update
    action: creation
  absent:
    verb: Remove
    action: deletion
  exists:
    verb: Already Exists
    action: exists
  enabled:
    verb: Enabled
    action: enabled
  disabled:
    verb: Disabled
    action: disabled
...
