---
- name: handle_error | Handle Errors Block
  when: __cas_job_async_result is defined and __cas_job_async_result.status is defined and __cas_job_async_result.status == 'failed'
  block:
    - name: handle_error | Show error and stop execution
      no_log: "{{ cas_secure_logging }}"
      when: not (cas_collect_logs | bool or cas_collect_errors | bool)
      vars:
        __cas_response: "{{ __cas_job_async_result['response'] | default({}) }}"
        __cas_response_detail: >-
          {% if __cas_response['json'] is defined %}
          | API response: {{ __cas_response['json'] | to_json }}
          {% elif __cas_response['status_code'] is defined %}
          | Status code: {{ __cas_response['status_code'] }}
          {% endif %}
      ansible.builtin.fail:
        msg: "error: {{ __cas_job_async_result['msg'] | default(__cas_job_async_result['detail'] | default(__cas_job_async_result['error'] | default('Unknown Error'))) }} {{ __cas_response_detail | trim }}"

    - name: handle_error | Extract item details from loop variable
      vars:
        __cas_loop_var: "{{ cas_job_async_results_item.ansible_loop_var }}"
        __cas_loop_item: "{{ cas_job_async_results_item[__cas_loop_var] }}"
        __cas_known_fields:
          - name
          - organization
          - hostname
          - source_credential
          - target_credential
          - inventory
          - role
          - user
          - username
          - groups
          - namespace
          - path
        __cas_present_fields: "{{ __cas_known_fields | select('in', __cas_loop_item.keys()) | list }}"
      ansible.builtin.set_fact:
        __cas_job_async_item: >-
          {{ dict(__cas_present_fields
              | zip(__cas_present_fields | map('extract', __cas_loop_item))
              | selectattr('1', 'ne', None)
              | list)
          }}

    - name: handle_error | Build consolidated list of failed objects and the error
      no_log: "{{ cas_secure_logging }}"
      vars:
        __cas_response: "{{ __cas_job_async_result['response'] | default({}) }}"
        __new_error: >-
          {{ __cas_job_async_item
              | combine({
                  'ERROR_MESSAGE': __cas_job_async_result['msg'] | default(__cas_job_async_result['detail'] | default(__cas_job_async_result['error'] | default('UNKNOWN ERROR'))),
                  'ERROR_STATUS_CODE': __cas_response['status_code'] | default(omit),
                  'ERROR_RESPONSE': __cas_response['json'] | default(omit),
                })
          }}
      ansible.builtin.set_fact:
        aap_configuration_role_errors: "{{ aap_configuration_role_errors | default({})
                                              | ansible.builtin.combine(
                                                  { cas_error_list_var_name: aap_configuration_role_errors[cas_error_list_var_name]
                                                      | default([]) + [__new_error]
                                                  }
                                                )
                                        }}"
...
