---
- name: Manage Controller Labels Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_labels_secure_logging }}"
  block:
    - name: Labels | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_labels_async_concurrency | int }}"

    - name: Labels | Process in batches
      ansible.builtin.include_tasks:
        file: process_label_batch.yml
      loop: "{{ range(0, controller_labels | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ ((controller_labels | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __controller_label_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __controller_label_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __labels_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __controller_label_job_async_results_item
        label: "Cleaning up job results file: {{ __controller_label_job_async_results_item.results_file | default('Unknown') }}"
...
