---
- name: async_hub_group | An async_hub_group block
  block:
    - name: async_hub_group | Managing hub group | Wait for finish the hub group operation
      ansible.builtin.async_status:
        jid: "{{ __groups_job_async_result_item.ansible_job_id }}"
      register: __groups_job_async_result
      until: __groups_job_async_result.finished
      retries: "{{ hub_configuration_group_async_retries }}"
      delay: "{{ hub_configuration_group_async_delay }}"
  rescue:
    - name: async_hub_group | Load error details
      ansible.builtin.include_vars:
        file: "{{ __groups_job_async_result.results_file }}"
        name: __error_data

    - name: async_hub_group | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_hub_group | Building list of not processed hub group
      ansible.builtin.set_fact:
        __hub_group_error_list: "{{ __hub_group_error_list | default([]) + [
                                                                            {
                                                                             'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                             'error': __error_data['msg'] | default('')
                                                                            }
                                                                           ]
                                }}"
...