---
- name: include_wildcard_vars | Combine wildcard vars
  vars:
    all_vars:
      - gateway_authenticators
      - gateway_authenticator_maps
      - gateway_settings
      - aap_organizations
      - aap_applications
      - gateway_http_ports
      - gateway_service_clusters
      - gateway_service_keys
      - gateway_service_nodes
      - gateway_services
      - aap_teams
      - aap_user_accounts
      - gateway_role_definitions
      - gateway_role_team_assignments
      - gateway_role_user_assignments
      - gateway_routes
      - hub_namespaces
      - hub_collections
      - hub_collection_list
      - hub_custom_collections
      - hub_ee_registries
      - hub_ee_repositories
      - hub_ee_repository_sync
      - hub_ee_images
      - hub_collection_remotes
      - hub_collection_repositories
      - controller_settings
      - controller_instances
      - controller_instance_groups
      - controller_labels
      - controller_credential_types
      - controller_credentials
      - controller_credential_input_sources
      - controller_execution_environments
      - controller_notifications
      - controller_projects
      - controller_inventories
      - controller_inventory_sources
      - controller_hosts
      - controller_bulk_hosts
      - controller_groups
      - controller_templates
      - controller_workflows
      - controller_schedules
      - controller_roles
      - controller_launch_jobs
      - controller_workflow_launch_jobs
      - eda_credential_types
      - eda_credentials
      - eda_credential_input_sources
      - eda_controller_tokens
      - eda_projects
      - eda_event_streams
      - eda_decision_environments
      - eda_rulebook_activations
    var_name: "{{ item | regex_replace('^(' + all_vars | join('|') + ')_.*', '\\1') }}"
    curr_val: "{{ lookup('ansible.builtin.vars', item) }}"
    is_dict: "{{ true if curr_val is mapping else false }}"
    prev_val: "{{ lookup('ansible.builtin.vars', var_name, default={} if is_dict else []) }}"
  ansible.builtin.set_fact:
    "{{ var_name }}": "{{ prev_val | combine(curr_val, list_merge='append', recursive=true)
                          if is_dict else
                          (prev_val + curr_val) | unique }}"
  loop: "{{ query('ansible.builtin.varnames', '^(' + all_vars | join('|') + ')_.*') }}"
  when: not item.endswith('_secure_logging')
  tags: always

...
