---
- name: Manage Credential Types Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_credential_types_secure_logging }}"
  block:
    - name: Credential Types | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_credential_types_async_concurrency | int }}"

    - name: Credential Types | Process in batches
      ansible.builtin.include_tasks:
        file: process_credential_type_batch.yml
      loop: "{{ range(0, (credential_types if credential_types is defined else controller_credential_types) | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ (((credential_types if credential_types is defined else controller_credential_types) | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __credentialtypes_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __credentialtypes_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __credentialtypes_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __credentialtypes_job_async_result_item
        label: "Cleaning up job results file: {{ __credentialtypes_job_async_result_item.results_file | default('Unknown') }}"
...
