---
- name: async_gateway_authenticator | An async_gateway_authenticator block
  block:
    - name: async_gateway_authenticator | Managing Gateway Applications | Wait for finish the applications management
      ansible.builtin.async_status:
        jid: "{{ __gateway_authenticators_job_async_results_item.ansible_job_id }}"
      register: __gateway_authenticators_job_async_result
      until: __gateway_authenticators_job_async_result.finished
      retries: "{{ gateway_authenticators_async_retries }}"
      delay: "{{ gateway_authenticators_async_delay }}"
  rescue:
    - name: async_gateway_authenticator | Load error details
      ansible.builtin.include_vars:
        file: "{{ __gateway_authenticators_job_async_result.results_file }}"
        name: __error_data

    - name: async_gateway_authenticator | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_gateway_authenticator | Building list of not processed applications
      ansible.builtin.set_fact:
        __gateway_authenticators_error_list: "{{ __gateway_authenticators_error_list | default([]) + [
                                                                                  {
                                                                                   'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                   'error': __error_data['msg'] | default('')
                                                                                  }
                                                                                 ]
                                             }}"
...
