---
- name: Manage Inventory Sources Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_inventory_sources_secure_logging }}"
  block:
    - name: Inventory Sources | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_inventory_sources_async_concurrency | int }}"

    - name: Inventory Sources | Process in batches
      ansible.builtin.include_tasks:
        file: process_inventory_source_batch.yml
      loop: "{{ range(0, (inventory_sources if inventory_sources is defined else controller_inventory_sources) | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ (((inventory_sources if inventory_sources is defined else controller_inventory_sources) | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __inventory_source_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __inventory_source_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __inventory_sources_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __inventory_source_job_async_results_item
        label: "Cleaning up job results file: {{ __inventory_source_job_async_results_item.results_file | default('Unknown') }}"
...
