---
# Create Controller Execution Environments
- name: Manage Controller Execution Environments Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_execution_environments_secure_logging }}"
  block:
    - name: Execution Environments | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ controller_configuration_execution_environments_async_concurrency | int }}"

    - name: Execution Environments | Process in batches
      ansible.builtin.include_tasks:
        file: process_ee_batch.yml
      loop: "{{ range(0, (execution_environments if execution_environments is defined else controller_execution_environments) | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ (((execution_environments if execution_environments is defined else controller_execution_environments) | length - 1) / __batch_size | int) + 1 }}"
      when: controller_execution_environments is defined

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __execution_environments_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __execution_environments_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __execution_environments_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __execution_environments_job_async_results_item
        label: "Cleaning up job results file: {{ __execution_environments_job_async_results_item.results_file | default('Unknown') }}"
...
