---
- name: async_gateway_http_port | An async_gateway_http_port block
  block:
    - name: async_gateway_http_port | Managing Gateway HTTP Ports | Wait for finish the HTTP port management
      ansible.builtin.async_status:
        jid: "{{ __gateway_http_ports_job_async_results_item.ansible_job_id }}"
      register: __gateway_http_ports_job_async_result
      until: __gateway_http_ports_job_async_result.finished
      retries: "{{ gateway_http_ports_async_retries }}"
      delay: "{{ gateway_http_ports_async_delay }}"
  rescue:
    - name: async_gateway_http_port | Load error details
      ansible.builtin.include_vars:
        file: "{{ __gateway_http_ports_job_async_result.results_file }}"
        name: __error_data

    - name: async_gateway_http_port | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_gateway_http_port | Building list of not processed HTTP ports
      ansible.builtin.set_fact:
        __gateway_http_ports_error_list: "{{ __gateway_http_ports_error_list | default([]) + [
                                                                                  {
                                                                                   'port': __error_data['invocation']['module_args']['port'] | default(''),
                                                                                   'error': __error_data['msg'] | default('')
                                                                                  }
                                                                                 ]
                                         }}"
...
