---
- name: async_hub_collection | An async_hub_collection block
  block:
    - name: async_hub_collection | Managing Hub collection | Wait for finish the hub collection operation
      ansible.builtin.async_status:
        jid: "{{ __collections_job_async_result_item.ansible_job_id }}"
      register: __collections_job_async_result
      until: __collections_job_async_result.finished
      retries: "{{ hub_configuration_collection_async_retries }}"
      delay: "{{ hub_configuration_collection_async_delay }}"
  rescue:
    - name: async_hub_collection | Load error details
      ansible.builtin.include_vars:
        file: "{{ __collections_job_async_result.results_file }}"
        name: __error_data

    - name: async_hub_collection | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_hub_collection | Building list of not processed hub collection
      ansible.builtin.set_fact:
        __hub_collection_error_list: "{{ __hub_collection_error_list | default([]) + [
                                                                                  {
                                                                                   'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                   'error': __error_data['msg'] | default('')
                                                                                  }
                                                                                 ]
                                            }}"
...