---
- name: Managing Role Based Access Entries on Controller
  ansible.controller.role_definition:
    name: "{{ __controller_role_def_item.0.name | default(__controller_role_def_item.name) | default(omit, true) }}"
    permissions: "{{ __controller_role_def_item.0.permissions | default(__controller_role_def_item.permissions) | default(([] if controller_configuration_role_def_enforce_defaults else omit), true) }}"
    content_type: "{{ __controller_role_def_item.0.content_type | default(__controller_role_def_item.content_type) }}"
    description: "{{ __controller_role_def_item.0.description | default(__controller_role_def_item.description) | default(('' if controller_configuration_role_def_enforce_defaults else omit), true) }}"
    state: "{{ __controller_role_def_item.0.state | default(__controller_role_def_item.state) | default(platform_state | default('present')) }}"

    # Role Standard Options
    controller_username: "{{ aap_username | default(omit, true) }}"
    controller_password: "{{ aap_password | default(omit, true) }}"
    controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
    request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    controller_host: "{{ aap_hostname | default(omit, true) }}"
    validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ (controller_role_definitions }}"
  loop_control:
    loop_var: __controller_role_def_item
    label: "{{ __operation.verb }} Role Based Access Entry on Controller {{ __controller_role_def_item.1 | default(__controller_role_def_item.name) }}"
    pause: "{{ controller_configuration_role_def_loop_delay }}"
  no_log: "{{ controller_configuration_role_def_async_retries }}"
  async: "{{ ansible_check_mode | ternary(0, 1000) }}"
  poll: 0
  register: __controller_role_def_job_async
  changed_when: (__controller_role_def_job_async.changed if ansible_check_mode else false)
  vars:
    __operation: "{{ operation_translate[__controller_role_def_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"

- name: Flag for errors (check mode only)
  ansible.builtin.set_fact:
    error_flag: true
  when: ansible_check_mode and __controller_role_def_job_async.failed is defined and __controller_role_def_job_async.failed

- name: Managing Role Definitions | Wait for finish the Roles management
  ansible.builtin.async_status:
    jid: "{{ __controller_role_def_job_async_results_item.ansible_job_id }}"
  register: __controller_role_def_job_async_result
  until: __controller_role_def_job_async_result.finished
  retries: "{{ controller_configuration_role_def_async_retries }}"
  delay: "{{ controller_configuration_role_def_async_delay }}"
  loop: "{{ __controller_role_def_job_async.results }}"
  loop_control:
    loop_var: __controller_role_def_job_async_results_item
    label: "{{ __operation.verb }} Role Definition {{ __controller_role_def_job_async_results_item.__controller_role_def_item.1 | default(__controller_role_def_job_async_results_item.__controller_role_def_item.name) }} | Wait for finish the Role definitions {{ __operation.action }}"
  when: not ansible_check_mode and __controller_role_def_job_async_results_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_role_def_async_retries }}"
  vars:
    __operation: "{{ operation_translate[__controller_role_def_job_async_results_item.__controller_role_def_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
...
