---
- name: Manage Gateway Teams Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ gateway_teams_secure_logging }}"
  block:
    - name: Teams | Set batch size
      ansible.builtin.set_fact:
        __batch_size: "{{ gateway_teams_async_concurrency | int }}"

    - name: Teams | Process in batches
      ansible.builtin.include_tasks:
        file: process_team_batch.yml
      loop: "{{ range(0, aap_teams | length, __batch_size | int) | list }}"
      loop_control:
        loop_var: __batch_start_index
        label: "Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }} of {{ ((aap_teams | length - 1) / __batch_size | int) + 1 }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __team_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __team_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __gateway_teams_batch_async.results | default([]) }}"
      loop_control:
        loop_var: __team_job_async_results_item
        label: "Cleaning up job results file: {{ __team_job_async_results_item.results_file | default('Unknown') }}"
...
