---
- name: process_team_batch | Get current batch
  ansible.builtin.set_fact:
    __current_batch: "{{ aap_teams[__batch_start_index | int : __batch_start_index | int + __batch_size | int] }}"

- name: process_team_batch | Configuration (Batch {{ (__batch_start_index | int / __batch_size | int) + 1 }})
  ansible.platform.team:
    name: "{{ __gateway_teams_item.name | mandatory }}"
    new_name: "{{ __gateway_teams_item.new_name | default(omit) }}"
    description: "{{ __gateway_teams_item.description | default(omit) }}"
    organization: "{{ __gateway_teams_item.organization | default(omit) }}"
    new_organization: "{{ __gateway_teams_item.new_organization | default(omit) }}"
    state: "{{ __gateway_teams_item.state | default(platform_state | default(omit, true)) }}"
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ __current_batch }}"
  loop_control:
    loop_var: __gateway_teams_item
    label: "{{ __operation.verb }} Gateway team {{ __gateway_teams_item.name }}"
    pause: "{{ gateway_teams_loop_delay }}"
  async: 1000
  poll: 0
  register: __gateway_teams_batch_async
  changed_when: not __gateway_teams_batch_async.changed
  vars:
    __operation: "{{ operation_translate[__gateway_teams_item.state | default(platform_state) | default('present')] }}"

- name: process_team_batch | Wait for batch to complete
  ansible.builtin.include_role:
    name: infra.aap_configuration.collect_async_status
  loop: "{{ __gateway_teams_batch_async.results }}"
  loop_control:
    loop_var: __gateway_teams_job_async_results_item
    label: "{{ __operation.verb }} Gateway team {{ __gateway_teams_job_async_results_item.__gateway_teams_item.name }} | Wait for finish the team {{ __operation.action }}"
  when:
    - not ansible_check_mode
    - __gateway_teams_job_async_results_item.ansible_job_id is defined
  vars:
    cas_secure_logging: "{{ gateway_teams_secure_logging }}"
    cas_async_delay: "{{ gateway_teams_async_delay }}"
    cas_async_retries: "{{ gateway_teams_async_retries }}"
    cas_job_async_results_item: "{{ __gateway_teams_job_async_results_item }}"
    cas_register_subvar: gateway_teams
    cas_error_list_var_name: "gateway_teams_errors"
    __operation: "{{ operation_translate[__gateway_teams_job_async_results_item.__gateway_teams_item.state | default(platform_state) | default('present')] }}"
    cas_object_label: "{{ __operation.verb }} Gateway team {{ __gateway_teams_job_async_results_item.__gateway_teams_item.name }} | Wait for finish the team {{ __operation.action }}"
...
