---
# https://github.com/marketplace/actions/issues-helper
name: Check inactive
permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@200c78641dbf33838311e5a1e0c31bbdb92d7cf0 # v3
        with:
          actions: 'check-inactive'
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 30
          issue-state: open
          exclude-labels: 'new,enhancement,backlog,help wanted,module-issue,blocked - upstream'
...
