---
# https://github.com/marketplace/actions/issues-helper
name: Check and close inactive

permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  close-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@200c78641dbf33838311e5a1e0c31bbdb92d7cf0 # v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'inactive'
          inactive-day: 7
...
