---
name: pre-commit and sanity tests

on:
  push:
    branches: [devel]
  pull_request_target:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  approve_run:
    environment: requires-approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval granted."

  pre-commit:
    needs: approve_run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.x"
      - name: Run default pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          ANSIBLE_GALAXY_SERVER_LIST: certified,galaxy
          ANSIBLE_GALAXY_SERVER_CERTIFIED_URL: https://console.redhat.com/api/automation-hub/content/published/
          ANSIBLE_GALAXY_SERVER_CERTIFIED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN: ${{ secrets.CRC_PUBLISH_KEY }}
          ANSIBLE_GALAXY_SERVER_GALAXY_URL: https://galaxy.ansible.com/api/
      - name: Install system dependencies for EDA collection
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libsystemd-dev pkg-config libkrb5-dev
      - name: Run sanity (manual stage)
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --hook-stage manual sanity --all-files
        env:
          ANSIBLE_GALAXY_SERVER_LIST: certified,galaxy
          ANSIBLE_GALAXY_SERVER_CERTIFIED_URL: https://console.redhat.com/api/automation-hub/content/published/
          ANSIBLE_GALAXY_SERVER_CERTIFIED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN: ${{ secrets.CRC_PUBLISH_KEY }}
          ANSIBLE_GALAXY_SERVER_GALAXY_URL: https://galaxy.ansible.com/api/
